Repository wutpppppppppppppppppp/tcm-web, pull requests merged in 2025-01, with the labels that each got.

#4 Feat product
  package-lock.json
  package.json
  public/assets/images/Bentonite.jpeg
  public/assets/images/Graphite.jpeg
  public/assets/images/Graphite_2.jpeg
  public/assets/images/MgCO3.jpeg
  public/assets/images/MgCO3_2.jpeg
  public/assets/images/MgCO3_3.jpeg
  public/assets/images/MgO_200.jpeg
  public/assets/images/MgO_200_2.jpeg
  public/assets/images/MgO_200_3.jpeg
  public/assets/images/Talc_1250.jpeg
  public/assets/images/Talc_30.jpeg
  public/assets/images/Talc_35.jpeg
  public/assets/images/banner-1.png
  public/assets/images/banner-2.png
  public/p300.png
  src/app/[locale]/(marketing)/catalog/[slug]/page.tsx
  src/app/[locale]/(marketing)/catalog/page.tsx
  src/components/CatalogCard.tsx
  src/components/LineIcon.tsx
  src/components/SocialBtn.tsx
  src/locales/en.json
  src/locales/th.json
  src/locales/zh.json
  src/styles/global.css
Labels: enhancement, chore

#5 Feat landing
  package-lock.json
  package.json
  public/assets/images/MgO_200_3.jpeg
  public/assets/images/Powder-four.jpg
  public/assets/images/Powder-one.jpg
  public/assets/images/Powder-three.jpg
  public/assets/images/Powder-two.jpg
  public/assets/images/Talc_1250.jpeg
  src/app/[locale]/(marketing)/about/page.tsx
  src/app/[locale]/(marketing)/layout.tsx
  src/app/[locale]/(marketing)/page.tsx
  src/components/CatalogCard.tsx
  src/components/LandingSwiper.tsx
  src/components/LineIcon.tsx
  src/components/ProductSwiper.tsx
  src/components/navbar.tsx
  src/locales/en.json
  src/locales/th.json
  src/locales/zh.json
  src/styles/custom-arrow.css
  src/styles/global.css
  src/templates/BaseTemplate.tsx
Labels: enhancement

#8 fix(i18n and css): i18n and css
  crowdin.yml
  eslint.config.mjs
  src/app/[locale]/(marketing)/about/page.tsx
  src/app/[locale]/(marketing)/contact/page.tsx
  src/app/[locale]/(marketing)/page.tsx
  src/locales/en.json
  src/locales/th.json
  src/locales/zh.json
Labels: enhancement

#13 feat(blur and css fix): add blur and css fix
  src/app/[locale]/(marketing)/about/page.tsx
  src/app/[locale]/(marketing)/page.tsx
  src/components/CatalogCard.tsx
  src/components/Footer.tsx
  src/components/ImageSlider.tsx
  src/components/LandingSwiper.tsx
  src/locales/en.json
  src/locales/th.json
Labels: documentation
